### ISSUE TITLE
Encryption context page... page has disappeared; links are now invalid

### ISSUE THREAD

**Issue by Andrew-Webb** [awsdocs/aws-kms-developer-guide#11]
I have https://docs.aws.amazon.com/kms/latest/developerguide/encrypt-context.html bookmarked.  Re-visiting it today, all it does is redirect to https://docs.aws.amazon.com/kms/latest/developerguide/overview.html

What happened to the Encryption Context page?  I notice that the link is used in many pages in the documentation (e.g. [this one](https://aws.amazon.com/premiumsupport/knowledge-center/kms-encryption-context/)), but the target page itself seems to have vanished.

**Comment by juneb** [comment]
Thanks for the feedback. Sorry about breaking your bookmark. 

The general industry definition of _encryption context_ is in our new [Cryptographic Tools and Services](https://docs.aws.amazon.com/crypto/latest/userguide/awscryp-overview.html) guide. This definition also explains how different AWS tools and services use the term: [encryption context](https://docs.aws.amazon.com/crypto/latest/userguide/cryptography-concepts.html#define-encryption-context).

We wrote this new guide to help people distinguish the AWS crypto tools and services and decide which one is right for each use case. Let me know if it's helpful. 

The KMS-specific discussion of encryption context, which was split across three sections, is now all in one place in the concepts section:  [encryption context](https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#encrypt_context). 

Hope this helps!

**Comment by Andrew-Webb** [comment]
OK thanks; I'll check out the new pages.

There is obviously still a clean-up task for pages with the old link, e.g. https://aws.amazon.com/premiumsupport/knowledge-center/kms-encryption-context/ - plus I came across others.

**Comment by juneb** [comment]
Thanks! Instead of tracking these down, I'm going to set up a redirect. I didn't do that because I wanted people to see both the cross-service and KMS-specific definitions, but that's impractical. 

Again, thx for the feedback. I always helps.
