### ISSUE TITLE
Broken permalink in AWS KMS Best Practices

### ISSUE THREAD

**Issue by michael-k** [awsdocs/aws-kms-developer-guide#13]
### Broken permalink

The *AWS Key Management Service Best Practices* available under https://d1.awsstatic.com/whitepapers/aws-kms-best-practices.pdf (referenced at https://aws.amazon.com/whitepapers/) mention on their last page

    For the most up-to-date version of this white paper, please visit:
    https://d0.awsstatic.com/whitepapers/KMS-Best-Practices.pdf

This link responds with status code 403 Forbidden.

### Additional broken links

Also the last three links in the notes are broken.  The visible URLs are correct, but the underlying links represent the `#` with `%23` leading to broken links on both Firefox and Chromium.

**Comment by juneb** [comment]
Thanks! That PDF isn't a part of this repo, but I'll file an internal bug to fix that link.
