### ISSUE TITLE
Graphic - Reduces the risk of the CMK becoming unmanageable.

### ISSUE THREAD

**Issue by omenking** [awsdocs/aws-kms-developer-guide#15]
I would like to put forward this graphical representation for this scenario.
Here's a mockup of how it would look in the documentation:

I used graphics elements exclusively from the AWS Kit to avoid any concerns of ownership third-party assets.

<img width="806" alt="Screen Shot 2019-08-01 at 8 09 22 AM" src="https://user-images.githubusercontent.com/7776/62292189-d1efdb80-b433-11e9-8d93-e1a36ca313d0.png">

I have attached the Adobe XD file which allows for future modification.
I created the source file in Adobe XD since the software is free to use.

[Reduces-the-risk-of-the-CMK-becoming-unmanageable.zip](https://github.com/awsdocs/aws-kms-developer-guide/files/3456589/Reduces-the-risk-of-the-CMK-becoming-unmanageable.zip)

Here is the rendered graphic as a png

<img width="1106" alt="Screen Shot 2019-08-01 at 1 45 58 PM" src="https://user-images.githubusercontent.com/7776/62315183-cff14100-b462-11e9-9f47-bab576cfc236.png">

When I have a moment I'll submit a pull request

**Comment by omenking** [comment]
I did some research to determine how to insert an image as a pull request so I looked up  the documentation which included an image:

So here in the Aurora documentation, we have the following:

<img width="1068" alt="Screen Shot 2019-08-01 at 9 13 40 AM" src="https://user-images.githubusercontent.com/7776/62296239-ac1b0480-b43c-11e9-9504-51cc9f6e9ac7.png">

Here's the dilemma. The github docs repo does not contain any images, and they appear to be hosted via  `http://docs.aws.amazon.com/` See as follows:

```
(http://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/images/AuroraArch001.png)
```

This is my current thoughts on why images are not included in the repo themselves:
* I am looking at an old image before AWS docs being open-sourced and maybe images are included in the repo now
* images are served via CloudFront of the process of including images in the documentation follows a different procedure
* images could contain malicious payloads so they need to be audited before their inclusion

I would very much like to know so I can create an put forward more graphical diagrams.

**Comment by juneb** [comment]
Thanks, Andrew! I'd definitely welcome graphics like these in the KMS Developer Guide. The reason that you don't see an *images* directory, or something like it is that the markdown files in this repository are the product of our build system, not its source. The source is XML files with embedded graphics.

But that shouldn't be a problem. If you submit a diagram here, I can add it to the XML, build, and refresh the markdown files.

**Comment by omenking** [comment]
Excellent, how is this for information? :

The url in question:
```
https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-upgrading.html
````
The markdown file:
```
key-policies.md
```

Insertion point (after line 58):
```
**1\. Reduces the risk of the CMK becoming unmanageable\.**  
You cannot delete your AWS account's root user, so allowing access to this user reduces the risk of the CMK becoming unmanageable\. Consider this scenario:  

<HERE> 

1. A CMK's key policy allows *only* one IAM user, Alice, to manage the CMK\. This key policy does not allow access to the root user\.
```

The image:
<img width="985" alt="Reduces-the-risk-of-the-CMK-becoming-unmanageable" src="https://user-images.githubusercontent.com/7776/62312499-5191a080-b45c-11e9-9132-7a74b70db051.png">

**Comment by juneb** [comment]
Thanks. I'm not a graphical learner, but I'm just wondering if this point really requires a diagram. It seems pretty simple and I don't want anyone to think it's more complex than it is. 

Andrew, was anyone confused by this and required more information? 

I'd really appreciate other opinions here. Everyone is welcome to comment. I'll ask our editors, too.

**Comment by YiddishNinja** [comment]
Haven't evaluated it against process, but item 2 has a typo: "unmangable."

**Comment by SalusaSecondus** [comment]
I am a somewhat visual learner and like diagrams/charts. However, I'm inclined to agree with @juneb that this point is sufficiently simple that a diagram does not help explain it and may simply confuse matters more.

**Comment by juneb** [comment]
> Haven't evaluated it against process, but item 2 has a typo: "unmangable."

I grepped the repo for that misspelling, but it's not found.

**Comment by omenking** [comment]
@YiddishNinja  corrected spelling, thank you. This is my fault. Grammarly does not operate within Adobe XD.

### Practical
IAM Policies are confusing, as a practical developer I want to see these whenever possible to help understand the context.

### Visual
It made sense to me once I made the graphic. Since this is a case where the root user does not implicitly inherit resources the graphic further emphasizes this deviation for normal expectations.

**Comment by mattsb42-aws** [comment]
As a very visual learner, I'm actually going to break with the pack here and say I think that this diagram does make it simpler to grasp the issue being conveyed. It does not introduce any new information, but I get the meaning at a glance rather than from parsing several paragraphs of text.

I think that this would lower the barrier to entry for grasping the concept for at least some of our customers.

My only issue, personally, is the use of the root user as a stand-in for the account, but it looks like that is just carrying over the convention used in the text.

**Comment by juneb** [comment]
Thanks, @mattsb42-aws. The ":root" suffix is part of the [account ARN](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-arns). However, in this case, we really are referring to the [account root user](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-user.html), which is the only IAM identity that cannot be deleted from the account.

**Comment by mattsb42-aws** [comment]
> in this case, we really are referring to the account root user, which is the only IAM identity that cannot be deleted from the account.

Ahh, ok. That makes sense, thanks.

**Comment by scotdunn** [comment]
I agree with @juneb. I believe the explanation alone is more clear without the graphic. It took me a while to study the graphic to figure out what it was saying.  But when I read the text below it, I got the concept immediately.  I never did go back and see if I could understand how the diagram was trying to convey the same information.  If anything, I think it muddies the water.

I totally support having more helpful diagrams to explain concepts and am frequently asked to produce such diagrams myself.  But this is one case where I think the art is not warranted.

**Comment by omenking** [comment]
I'm defeated. I'm closing the ticket.

**Comment by omenking** [comment]
That graphic took 10mins, I don't care if it's included and would rather move onto where I can contribute. 

My dilemma is I don't have an **objective criteria** provided to determine what documentation could benefit from a visual aid/technical diagram. 

KMS is challenging and I see the need for graphics everywhere.

@juneb would you please do me the favour of putting forward one case in the KMS documentation that would be enhanced with a graphic.

I am not adept at written communication so my apologies if my written tone is argumentive or other negative nature. My writing style is strongly supported by Grammarly so and the bi-product is a draconian written tone.

**Comment by juneb** [comment]
Thanks, @omenking! You're written tone is fine and I'm really looking forward to working with you to provide better graphics. 

Just off the top of my head, we could use nice graphics for:
* Importing Keys (several places in this doc
   https://docs.aws.amazon.com/kms/latest/developerguide/importing-keys.html 

* Encryption SDK workflow description. We had diagrams, but adding the CMM made the diagrams very complex.
   https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/how-it-works.html

I'm sure there are more, but I would really appreciate diagrams in these topics.  Thanks!

**Comment by omenking** [comment]
Excellent to hear, I'll investigate these pages.
May I also suggestion in addition to that I can refresh the existing graphics to be in-line with the new architectural styling guide.

**Comment by juneb** [comment]
Thanks! AWS designed a set of [icons for PowerPoint](https://aws.amazon.com/architecture/icons/). 

Also, feel free to copy the icons that we use in our current diagrams. For example:
* https://docs.aws.amazon.com/kms/latest/developerguide/services-wm.html#wm-encrypt
* https://docs.aws.amazon.com/kms/latest/developerguide/services-dynamodb.html#dynamodb-encrypt
* https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/choose-keyring.html#using-keyrings
* https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/data-caching-details.html#how-caching-works

And, honestly, if you can come up with a nice design that communicates the concepts, it's easier for us to swap an icon than it is to design the graphic.

Thanks again. I really appreciate the help.
