### ISSUE TITLE
Do you use KB instead of KiB on purpose?

### ISSUE THREAD

**Issue by onnadi-sa** [awsdocs/aws-kms-developer-guide#18]
In a few places you use the unit KB and immediately after put the number of bytes in parentheses e.g.

* https://docs.aws.amazon.com/kms/latest/developerguide/limits.html
* https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html

Changing KB to KiB would remove the need to write out the number of bytes. 

Shall I create a pull request for that?

**Comment by juneb** [comment]
Closing this issue, but I really appreciate your contributions and feedback. Looking forward to working with you more to improve the docs.
