### ISSUE TITLE
Broken links to topics in KMS API Reference

### ISSUE THREAD

**Issue by MaksimAniskov** [awsdocs/aws-kms-developer-guide#22]
Following chapters contain malformed links to KMS API Reference.
[Concepts](../blob/master/doc_source/concepts.md)
[Changing a key policy](../blob/master/doc_source/key-policy-modifying.md)
[Using policy conditions with AWS KMS](../blob/master/doc_source/policy-conditions.md)
[How to choose your CMK configuration](../blob/master/doc_source/symm-asymm-choose.md)

Malformed links start with `url-kms-api;` which apparently was supposed to be replaced with `https://docs.aws.amazon.com/kms/latest/APIReference/`.

An example of broken link: `url-kms-api;API_PutKeyPolicy.html`

Correct value: `https://docs.aws.amazon.com/kms/latest/APIReference/API_PutKeyPolicy.html`

**Comment by juneb** [comment]
Thanks so much! I'll merge this, fix the source, and republish.

**Comment by juneb** [comment]
Fixed: https://github.com/awsdocs/aws-kms-developer-guide/commit/77cd3fb561bdeedbfa0bf805e86ed329e8e4c26c
