### ISSUE TITLE
Broken image on key policies page

### ISSUE THREAD

**Issue by bobbiec** [awsdocs/aws-kms-developer-guide#44]
On https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html (or https://github.com/awsdocs/aws-kms-developer-guide/blob/master/doc_source/key-policies.md in this repo), the image at the very bottom points at the URL https://docs.aws.amazon.com/kms/latest/developerguide/images/console-key-policy-full-sm.png , which 404s.

**Comment by juneb** [comment]
Thank you! I meant to remove the image (and the surrounding language) because the default key policy in the console doesn't show any configuration except for the user/role names that you choose. I'll fix that right away.

**Comment by juneb** [comment]
Fixed: https://github.com/awsdocs/aws-kms-developer-guide/commit/93e71d4510f87d29eb361f7f27e43fb9f2270840
