### ISSUE TITLE
Better clarification is needed for the Default KMS policy

### ISSUE THREAD

**Issue by zackriso** [awsdocs/aws-kms-developer-guide#52]
Hello, 

Under the section "Allows access to the AWS account and enables IAM policies" of the page https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-default.html, it is mentioned that: 

"It allows the account to use IAM policies to allow access to the KMS key, in addition to the key policy. _**Without this permission, IAM policies that allow access to the key are ineffective**_, although IAM policies that deny access to the key are still effective." 

While this is true, it gives, or might give the impression that without the default policy: 

```
{
  "Sid": "Enable IAM policies",
  "Effect": "Allow",
  "Principal": {
    "AWS": "arn:aws:iam::111122223333:root"
   },
  "Action": "kms:*",
  "Resource": "*"
}
```

then IAM access to the key is not possible. However, this is not 100% true, because if we for example allow a specific IAM user or IAM Role access to the KMS key through a custom Key policy, such as this one: 

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Describe the policy statement",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::111122223333:user/Alice"
      },
      "Action": "kms:*",
      "Resource": "*"
    }
  ]
}
```
then we are actually allowing IAM policies and users to the key, even without the "AWS": "arn:aws:iam::111122223333:root" entry. 

I believe this section should be reworded to mention that the default policy, and/or other IAM Principals (with an example) are needed to provide IAM-based access to the key itself. 

I hope my explanation is clear, thank you for your hard work and efforts.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
